# Generated by Django 4.2 on 2024-09-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('cv', models.FileField(blank=True, null=True, upload_to='')),
                ('image', models.ImageField(upload_to='images/')),
                ('facebook', models.URLField(max_length=500)),
                ('github', models.URLField(max_length=500)),
                ('telegram', models.URLField(max_length=500)),
                ('discord', models.URLField(max_length=500)),
            ],
        ),
    ]
